// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class SimpleTestTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void simpleTest() {
    driver.get("http://localhost:8080/");
    driver.manage().window().setSize(new Dimension(1590, 695));
    driver.findElement(By.cssSelector("#account-menu > span > span")).click();
    driver.findElement(By.cssSelector("#login > span")).click();
    driver.findElement(By.id("username")).sendKeys("admin");
    driver.findElement(By.id("password")).sendKeys("admin");
    driver.findElement(By.cssSelector(".btn")).click();
    driver.findElement(By.cssSelector("#account-menu > span > span")).click();
    driver.findElement(By.cssSelector("#logout > span")).click();
    driver.findElement(By.cssSelector("#account-menu > span > span")).click();
    driver.findElement(By.cssSelector("li:nth-child(2) > .dropdown-item > span")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("li:nth-child(2) > .dropdown-item > span"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.name("login")).click();
    driver.findElement(By.name("login")).sendKeys("testuser");
    driver.findElement(By.id("email")).sendKeys("testuser@example.com");
    driver.findElement(By.id("password")).sendKeys("testpassword");
    driver.findElement(By.id("confirmPassword")).sendKeys("testpassword");
    driver.findElement(By.cssSelector(".btn")).click();
    driver.findElement(By.cssSelector("#account-menu > span > span")).click();
    driver.findElement(By.cssSelector("#login > span")).click();
    driver.findElement(By.id("username")).sendKeys("testuser");
    driver.findElement(By.id("password")).sendKeys("testpassword");
    driver.findElement(By.cssSelector(".btn")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".btn"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.id("password")).click();
    driver.findElement(By.cssSelector(".btn")).click();
    driver.findElement(By.cssSelector("#account-menu > span > span")).click();
  }
}
